
package com.palazzisoft.gerbio.integrator.catalogo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSMGAltaNdpSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSMGAltaNdpSoap {


    /**
     * 
     * @param cliente
     * @param oPedido
     * @param password
     * @param usuario
     * @return
     *     returns com.palazzisoft.gerbio.integrator.catalogo.PedidoRequest
     */
    @WebMethod(operationName = "SendAltaPedido", action = "http://tempuri.org/SendAltaPedido")
    @WebResult(name = "SendAltaPedidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendAltaPedido", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.SendAltaPedido")
    @ResponseWrapper(localName = "SendAltaPedidoResponse", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.SendAltaPedidoResponse")
    public PedidoRequest sendAltaPedido(
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        String cliente,
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "oPedido", targetNamespace = "")
        OPedido oPedido);

}
