
package com.palazzisoft.gerbio.integrator.catalogo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSMGSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSMGSoap {


    /**
     * 
     * @param cliente
     * @param password
     * @param usuario
     * @return
     *     returns com.palazzisoft.gerbio.integrator.catalogo.ProductsRequest
     */
    @WebMethod(operationName = "GetCatalog", action = "http://tempuri.org/GetCatalog")
    @WebResult(name = "GetCatalogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCatalog", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetCatalog")
    @ResponseWrapper(localName = "GetCatalogResponse", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetCatalogResponse")
    public ProductsRequest getCatalog(
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        String cliente,
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param cliente
     * @param password
     * @param usuario
     * @return
     *     returns com.palazzisoft.gerbio.integrator.catalogo.ProductsRequest
     */
    @WebMethod(operationName = "GetStockPriceCatalog", action = "http://tempuri.org/GetStockPriceCatalog")
    @WebResult(name = "GetStockPriceCatalogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStockPriceCatalog", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetStockPriceCatalog")
    @ResponseWrapper(localName = "GetStockPriceCatalogResponse", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetStockPriceCatalogResponse")
    public ProductsRequest getStockPriceCatalog(
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        String cliente,
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param cliente
     * @param password
     * @param usuario
     * @return
     *     returns com.palazzisoft.gerbio.integrator.catalogo.CategoryRequest
     */
    @WebMethod(operationName = "GetCategories", action = "http://tempuri.org/GetCategories")
    @WebResult(name = "GetCategoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCategories", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetCategories")
    @ResponseWrapper(localName = "GetCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetCategoriesResponse")
    public CategoryRequest getCategories(
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        String cliente,
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param cliente
     * @param password
     * @param usuario
     * @return
     *     returns com.palazzisoft.gerbio.integrator.catalogo.BrandRequest
     */
    @WebMethod(operationName = "GetBrands", action = "http://tempuri.org/GetBrands")
    @WebResult(name = "GetBrandsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBrands", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetBrands")
    @ResponseWrapper(localName = "GetBrandsResponse", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetBrandsResponse")
    public BrandRequest getBrands(
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        String cliente,
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param cliente
     * @param password
     * @param usuario
     * @return
     *     returns com.palazzisoft.gerbio.integrator.catalogo.ErrorRequest
     */
    @WebMethod(operationName = "GetErrors", action = "http://tempuri.org/GetErrors")
    @WebResult(name = "GetErrorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetErrors", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetErrors")
    @ResponseWrapper(localName = "GetErrorsResponse", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetErrorsResponse")
    public ErrorRequest getErrors(
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        String cliente,
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param cliente
     * @param password
     * @param usuario
     * @return
     *     returns com.palazzisoft.gerbio.integrator.catalogo.ContentRequest
     */
    @WebMethod(operationName = "GetXMLContenido", action = "http://tempuri.org/GetXMLContenido")
    @WebResult(name = "GetXMLContenidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetXMLContenido", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetXMLContenido")
    @ResponseWrapper(localName = "GetXMLContenidoResponse", targetNamespace = "http://tempuri.org/", className = "com.palazzisoft.gerbio.integrator.catalogo.GetXMLContenidoResponse")
    public ContentRequest getXMLContenido(
        @WebParam(name = "cliente", targetNamespace = "http://tempuri.org/")
        String cliente,
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
